<script>
import SEO from '$lib/components/SEO/index.svelte'
import { host, authorInfo, WWW_URL } from '$lib/config'
import HeadingUnderline from '$lib/HeadingUnderline.svelte'

const { author } = authorInfo

const breadcrumbs = [
	{
		name: 'Home',
		slug: '/'
	}
]

const entityMeta = {
	url: `${WWW_URL}/`,
	faviconWidth: 512,
	faviconHeight: 512,
	caption: author
}

const seoProps = {
	entityMeta,
	breadcrumbs,
	title: 'Terms and Conditions | ',
	metadescription: 'Helps you to build an online brand in ecommerce',
	featuredImage:
		'https://repository-images.githubusercontent.com/213575283/f577b8bd-8edb-41ba-bfe5-36e65072e1f2',
	ogImage:
		'https://repository-images.githubusercontent.com/213575283/f577b8bd-8edb-41ba-bfe5-36e65072e1f2',
	ogSquareImage: '/icon.png',
	twitterImage:
		'https://repository-images.githubusercontent.com/213575283/f577b8bd-8edb-41ba-bfe5-36e65072e1f2',
	image:
		'https://repository-images.githubusercontent.com/213575283/f577b8bd-8edb-41ba-bfe5-36e65072e1f2'
}

let title = 'Misiki - Terms & Policy',
	meta = [
		{
			hid: 'description',
			name: 'description',
			content:
				'Misiki terms and policy are most suited for startups. We love to help people growing their business'
		},
		{
			hid: 'keywords',
			name: 'keywords',
			property: 'keywords',
			content:
				'javasctipt ecommerce, image optimization, lazy loading, seo, fast , search engine optimization, easy, headless, authentication, cart & checkout, tailwindcss, server rendered, proxy + api integrated, animations, stores lazy loading, loading indicators, carousel, instant search, faceted filters'
		},

		// OpenGraph data
		{
			hid: 'og:title',
			name: 'og_title',
			property: 'og:title',
			content: 'Misiki - Terms & Policy'
		},
		{
			hid: 'og:description',
			name: 'og_description',
			property: 'og:description',
			content:
				'Misiki terms and policy are most suited for startups. We love to help People growing their business'
		},

		// Twitter
		{
			name: 'twitter:title',
			content: 'Misiki - Terms & Policy'
		},
		{
			name: 'twitter:description',
			content:
				'Misiki terms and policy are most suited for startups. We love to help people growing their business'
		},
		{
			name: 'og_url',
			property: 'og:url',
			content: `${host}/terms`
		}
		// {
		//   name: 'og_image',
		//   property: 'og:image',
		//   content:
		//     (this.product &&
		//       this.settings &&
		//       this.settings.CDN_URL + this.product.img) ||
		//     this.settings.social_share,
		// },
		// {
		//   property: 'og:image:width',
		//   content: '600',
		// },
		// {
		//   property: 'og:image:height',
		//   content: '600',
		// },
		// {
		//   name: 'twitter:image:src',
		//   content:
		//     (this.product &&
		//       this.settings &&
		//       this.settings.CDN_URL + this.product.img) ||
		//     this.settings.open_graph_image,
		// },
		// Google / Schema.org markup:
	]
</script>

<SEO {...seoProps} />

<div class="min-h-screen bg-white">
	<div class="container mx-auto max-w-7xl">
		<div class="p-3 py-5 sm:p-10">
			<div
				class="mx-auto mb-5 flex max-w-max flex-col items-center justify-center text-gray-800 sm:mb-10">
				<h1 class="mb-5 text-xl font-bold text-primary-500 sm:text-2xl lg:text-3xl">
					TERMS & CONDITIONS
				</h1>

				<HeadingUnderline />
			</div>

			<h2 class="mb-5 text-lg font-semibold tracking-wide sm:text-xl">Terms of Use</h2>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Terms Of Use For Information Dissemination</h1>

				<p class="text-sm">
					This document is an electronic record in terms of the amended Information Technology Act,
					2000 and rules and regulation made thereunder. This electronic record is generated by a
					computer system and does not require any physical or digital signatures. This document is
					published in accordance with the provisions of Rule 3 (1) of the Information Technology
					(Intermediaries Guidelines) Rules, 2011 that require publishing the Terms for access or
					usage of AtoZ Cambodia Portal. This document meets the stipulations and conditions
					mentioned in Section 65B (2) of the Indian Evidence Act, 1872.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Tyour Acceptance of This Agreement</h1>

				<p class="text-sm">
					This is an agreement between you ("you" or "your") and AtoZ Cambodia. When you access or
					use any of the Platforms you agree to be bound by these Terms and Conditions ("Terms").
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Changes</h1>

				<p class="text-sm">
					We may periodically change the Terms and the Site without notice, and you are responsible
					for checking these Terms periodically for revisions. All amended Terms become effective
					upon our posting to the Site, and any use of the site after such revisions have been
					posted signifies your consent to the changes.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">How you may our materials</h1>

				<p class="mb-5 text-sm">
					We use a diverse range of information, text, photographs, designs, graphics, images, sound
					and video recordings, animation, content, advertisement and other materials and effects
					(collectively "Materials") for the search services on the Platforms. We provide the
					Material through the Platforms FOR YOUR PERSONAL AND NON-COMMERCIAL USE ONLY.
				</p>

				<p class="mb-5 text-sm">
					While every attempt has been made to ascertain the authenticity of the Platforms content,
					AtoZ Cambodia is not liable for any kind of damages, losses or action arising directly or
					indirectly, due to access and/or use of the content in the Platforms including but not
					limited to decisions based on the content in the Platforms which results in any loss of
					data, revenue, profits, property, infection by viruses etc.
				</p>

				<p class="text-sm">
					Accordingly, you may view, use, copy, and distribute the Materials found on the Platforms
					for internal, non-commercial, informational purposes only. You are prohibited from data
					mining, scraping, crawling, or using any process or processes that send automated queries
					to AtoZ Cambodia. You may not use the Platforms or any of them to compile a collection of
					listings, including a competing listing product or service. You may not use the Platforms
					or any Materials for any unsolicited commercial e-mail. Except as authorized in this
					paragraph, you are not being granted a license under any copyright, trademark, patent or
					other intellectual property right in the Materials or the products, services, processes or
					technology described therein. All such rights are retained by AtoZ Cambodia, its
					subsidiaries, parent companies, and/or any third party owner of such rights.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">How You May Use Our Marks</h1>

				<p class="text-sm">
					The AtoZ Cambodia company names and logos and all related products and service names,
					design marks and slogans are trademarks and service marks owned by and used under license
					from AtoZ Cambodia or its wholly owned subsidiaries. All other trademarks and service
					marks herein are the property of their respective owners. All copies that you make of the
					Materials on any of the Platforms must bear any copyright, trademark or other proprietary
					notice located on the respective Platforms that pertains to the material being copied. You
					are not authorized to use any AtoZ Cambodia name or mark in any advertising, publicity or
					in any other commercial manner without the prior written consent of AtoZ Cambodia.
					Requests for authorisation should be made to AtoZ Cambodia.io
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">How We May Use Information You Provid to Us</h1>

				<p class="text-sm">
					Do not send us any confidential or proprietary information. Except for any personally
					identifiable information that we agree to keep confidential as provided in our Privacy
					Policy, any material, including, but not limited to any feedback, data, answers,
					questions, comments, suggestions, ideas or the like, which you send to us will be treated
					as being non-confidential and nonproprietary. We assume no obligation to protect
					confidential or proprietary information (other than personally identifiable information)
					from disclosure and will be free to reproduce, use, and distribute the information to
					others without restriction. We will also be free to use any ideas, concepts, know-how or
					techniques contained in information that you send us for any purpose whatsoever including
					but not limited to developing, manufacturing and marketing products and services
					incorporating such information.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Reviews, Ratings & Comments by Users</h1>

				<p class="mb-5 text-sm">
					Since, AtoZ Cambodia provides information directory services through various mediums (SMS,
					WAP, E-Mail, Website, APP and voice or phone), your ("Users") use any of the
					aforementioned medium to post Reviews, Ratings and Comments about the AtoZ Cambodia
					services and also about the Advertiser's listed at AtoZ Cambodia is subject to additional
					terms and conditions as mentioned herein.
				</p>

				<p class="mb-5 text-sm">
					You are solely responsible for the content of any transmissions you make to the Site or
					any transmissions you make to any mediums offered by AtoZ Cambodia and any materials you
					add to the Site or add to any mediums offered by AtoZ Cambodia, including but not limited
					to transmissions like your Reviews, Ratings & Comments posted by you(the
					"Communications"). AtoZ Cambodia does not endorse or accept any of your Communication as
					representative of their (AtoZ Cambodia) views. By transmitting any public Communication to
					the Site, you grant AtoZ Cambodia an irrevocable, non-exclusive, worldwide, perpetual,
					unrestricted, royalty-free license (with the right to sublicense) to use, reproduce,
					distribute, publicly display, publicly perform, adapt, modify, edit, create derivative
					works from, incorporate into one or more compilations and reproduce and distribute such
					compilations, and otherwise exploit such Communications, in all Platforms now known or
					later developed.
				</p>

				<p class="mb-5 text-sm">
					You confirm and warrant that you have the right to grant these rights to AtoZ Cambodia .
					You hereby waive and grant to AtoZ Cambodia all rights including intellectual property
					rights and also "moral rights" in your Communications, posted at AtoZ Cambodia through any
					of the mediums of AtoZ Cambodia. AtoZ Cambodia is free to use all your Communications as
					per its requirements from time to time. You represent and warrant that you own or
					otherwise control all of the rights to the content that you post as Review, Rating or
					Comments; that the content is accurate; that use of the content you supply does not
					violate these Terms and will not cause injury to any person or entity. For removal of
					doubts it is clarified that, the reference to Communications would also mean to include
					the reviews, ratings and comments posted by your Friend's tagged by you. Also AtoZ
					Cambodia reserves the right to mask or unmask your identity in respect of your Reviews,
					Ratings & Comments posted by you.
				</p>

				<p class="mb-5 text-sm">
					AtoZ Cambodia has the right, but not the obligation to monitor and edit or remove any
					content posted by you as Review, Rating or Comments. AtoZ Cambodia cannot review all
					Communications made on and through any of the mediums of AtoZ Cambodia. However, AtoZ
					Cambodia reserves the right, but has no obligation, to monitor and edit, modify or delete
					any Communications (or portions thereof) which AtoZ Cambodia in its sole discretion deems
					inappropriate, offensive or contrary to any AtoZ Cambodia policy, or that violate this
					terms:
				</p>

				<div class="mb-5 text-sm">
					<h6 class="mb-5">
						AtoZ Cambodia reserves the right not to upload or distribute to, or otherwise publish
						through the Site or Forums any Communication which
					</h6>

					<ul class="ml-4 flex list-decimal flex-col gap-5">
						<li>
							is obscene, indecent, pornographic, profane, sexually explicit, threatening, or
							abusive;
						</li>

						<li>
							constitutes or contains false or misleading indications of origin or statements of
							fact;
						</li>

						<li>
							slanders, libels, defames, disparages, or otherwise violates the legal rights of any
							third party;
						</li>

						<li>causes injury of any kind to any person or entity;</li>

						<li>
							infringes or violates the intellectual property rights (including copyright, patent
							and trademark rights), contract rights, trade secrets, privacy or publicity rights or
							any other rights of any third party;
						</li>

						<li>violates any applicable laws, rules, or regulations;</li>

						<li>
							contains software viruses or any other malicious code designed to interrupt, destroy
							or limit the functionality of any computer software or hardware or telecommunications
							equipment;
						</li>

						<li>
							impersonates another person or entity, or that collects or uses any information about
							Site visitors.
						</li>
					</ul>
				</div>

				<p class="mb-5 text-sm">
					It is also clarified that, if there are any issues or claims due to your posts by way of
					Reviews, Ratings and Comments, then AtoZ Cambodia reserves the right to take appropriate
					legal action against you. Further, you shall indemnify and protect AtoZ Cambodia against
					such claims or damages or any issues, due to your posting of such Reviews, Ratings and
					Comments AtoZ Cambodia takes no responsibility and assumes no liability for any content
					posted by you or any third party on AtoZ Cambodia site or on any mediums of AtoZ Cambodia.
				</p>

				<p class="mb-5 text-sm">
					You further acknowledge that conduct prohibited in connection with your use of the Forums
					includes, but is not limited to, breaching or attempting to breach the security of the
					Site or any of the mediums of AtoZ Cambodia.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Privacy Policy</h1>

				<p class="text-sm">
					AtoZ Cambodia is committed to protecting the privacy and confidentiality of any personal
					information that it may request and receive from its clients, business partners and other
					users of the Website. To read our privacy policy statement regarding such personal
					information please refer to PRIVACY POLICY.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Content Disclaimer</h1>

				<p class="mb-5 text-sm">
					AtoZ Cambodia communicates information provided and created by advertisers, content
					partners, software developers, publishers, marketing agents, employees, users, resellers
					and other third parties. While every attempt has been made to ascertain the authenticity
					of the content on the platform, AtoZ Cambodia has no control over content, the accuracy of
					such content, integrity or quality of such content and the information on our pages, and
					material on the Platforms may include technical inaccuracies or typographical errors, and
					we make no guarantees, nor can we be responsible for any such information, including its
					authenticity, currency, content, quality, copyright compliance or legality, or any other
					intellectual property rights compliance, or any resulting loss or damage. Further, we are
					not liable for any kind of damages, losses or action arising directly or indirectly due to
					any content, including any errors or omissions in any content, access and/or use of the
					content on the Platforms or any of them including but not limited to content based
					decisions resulting in loss of data, revenue, profits, property, infection by viruses etc.
				</p>

				<p class="mb-5 text-sm">
					All of the data on products and promotions including but not limited to, the prices and
					the availability of any product or service or any feature thereof, is subject to change
					without notice by the party providing the product or promotion. You should use discretion
					while using the Platforms .
				</p>

				<p class="mb-5 text-sm">
					AtoZ Cambodia reserves the right, in its sole discretion and without any obligation, to
					make improvements to, or correct any error or omissions in, any portion of the Platforms.
					Where appropriate, we will endeavor to update information listed on the Website on a
					timely basis, but shall not be liable for any inaccuracies.
				</p>

				<p class="mb-5 text-sm">
					All rights, title and interest including trademarks and copyrights in respect of the
					domain name and Platforms content hosted on the Platforms are reserved with AtoZ Cambodia.
					Users are permitted to read, print or download text, data and/or graphics from the Website
					or any other Platforms for their personal use only. Unauthorized access, reproduction,
					redistribution, transmission and/or dealing with any information contained in the
					Platforms in any other manner, either in whole or in part, are strictly prohibited,
					failing which strict legal action will be initiated against such users.
				</p>

				<p class="mb-5 text-sm">
					Links to external Internet sites may be provided within the content on Website or other
					Platforms as a convenience to users. The listing of an external site does not imply
					endorsement of the site by AtoZ Cambodia or its affiliates. AtoZ Cambodia does not make
					any representations regarding the availability and performance of its Platforms or any of
					the external websites to which we provide links. When you click on advertiser banners,
					sponsor links, or other external links from the Website or other Platforms, your browser
					automatically may direct you to a new browser window that is not hosted or controlled by
					AtoZ Cambodia.
				</p>

				<p class="mb-5 text-sm">
					AtoZ Cambodia and its affiliates are not responsible for the content, functionality,
					authenticity or technological safety of these external sites. We reserve the right to
					disable links to or from third-party sites to any of our Platforms, although we are under
					no obligation to do so. This right to disable links includes links to or from advertisers,
					sponsors, and content partners that may use our Marks as part of a co-branding
					relationship.
				</p>

				<p class="mb-5 text-sm">
					Some external links may produce information that some people find objectionable,
					inappropriate, or offensive. We are not responsible for the accuracy, relevancy, copyright
					compliance, legality, or decency of material contained in any externally linked websites.
					We do not fully screen or investigate business listing websites before or after including
					them in directory listings that become part of the Materials on our Platforms, and we make
					no representation and assume no responsibility concerning the content that third parties
					submit to become listed in any of these directories.
				</p>

				<p class="mb-5 text-sm">
					All those sections in the Platforms that invite reader participation will contain views,
					opinion, suggestion, comments and other information provided by the general public, and
					AtoZ Cambodia will at no point of time be responsible for the accuracy or correctness of
					such information. AtoZ Cambodia reserves the absolute right to accept/reject information
					from readers and/or advertisements from advertisers and impose/relax Platforms access
					rules and regulations for any user(s).
				</p>

				<p class="mb-5 text-sm">
					AtoZ Cambodia also reserves the right to impose/change the access regulations of the
					Platforms , whether in terms of access fee, timings, equipment, access restrictions or
					otherwise, which shall be posted from time to time under these terms and conditions. It is
					the responsibility of users to refer to these terms and conditions each time they use the
					Platforms.
				</p>

				<p class="text-sm">
					While every attempt has been made to ascertain the authenticity of the content in the
					Platforms, AtoZ Cambodia is not liable for any kind of damages, losses or action arising
					directly or indirectly, due to access and/or use of the content in the Platforms including
					but not limited to any decisions based on content in the Platforms resulting in loss of
					data, revenue, profits, property, infection by viruses etc.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Warranty Disclaimer</h1>

				<p class="mb-5 text-sm">
					Please remember that any provider of goods or services is entitled to register with AtoZ
					Cambodia. AtoZ Cambodia does not examine whether the advertisers are good, reputable or
					quality sellers of goods / service providers. You must satisfy yourself about all relevant
					aspects prior to availing of the terms of service. AtoZ Cambodia has also not negotiated
					or discussed any terms of engagement with any of the advertisers. The same should be done
					by you. Purchasing of goods or availing of services from advertisers shall be at your own
					risk.
				</p>

				<p class="mb-5 text-sm">
					We do not investigate, represent or endorse the accuracy, legality, legitimacy, validity
					or reliability of any products, services, deals, coupons or other promotions or materials,
					including advice, ratings, and recommendations contained on, distributed through, or
					linked, downloaded or accessed from the Platforms.
				</p>

				<p class="mb-5 text-sm">
					References that we make to any names, marks, products or services of third parties or
					hypertext links to third party sites or information do not constitute or imply our
					endorsement, sponsorship or recommendation of the third party, of the quality of any
					product or service, advice, information or other materials displayed, purchased, or
					obtained by you as a result of an advertisement or any other information or offer in or in
					connection with the Platforms.
				</p>

				<p class="mb-5 text-sm">
					Any use of the Platforms, reliance upon any Materials, and any use of the Internet
					generally shall be at your sole risk. AtoZ Cambodia disclaims any and all responsibility
					or liability for the accuracy, content, completeness, legality, reliability, or
					operability or availability of information or material displayed in the search results in
					the Platforms.
				</p>

				<p class="mb-5 text-sm">
					THE MATERIAL AND THE PLATFORMS USED TO PROVIDE THE MATERIAL (INCLUDING THE WEBSITE ) ARE
					PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR
					IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
					MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. AtoZ Cambodia
					DISCLAIMS, TO THE FULLEST EXTENT PERMITTED UNDER LAW, ANY WARRANTIES REGARDING THE
					SECURITY, RELIABILITY, TIMELINESS, ACCURACY AND PERFORMANCE OF THE PLATFORMS AND
					MATERIALS. AtoZ Cambodia DOES NOT WARRANT THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR
					THAT THE CONTENT IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
				</p>

				<p class="text-sm">
					AtoZ Cambodia DISCLAIMS ANY AND ALL WARRANTIES TO THE FULLEST EXTENT OF THE LAW, INCLUDING
					ANY WARRANTIES FOR ANY INFORMATION, GOODS, OR SERVICES, OBTAINED THROUGH, ADVERTISED OR
					RECEIVED THROUGH ANY LINKS PROVIDED BY OR THROUGH THE PLATFORMS SOME COUNTRIES OR OTHER
					JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS
					MAY NOT APPLY TO YOU. YOU MAY ALSO HAVE OTHER RIGHTS THAT VARY FROM COUNTRY TO COUNTRY AND
					JURISDICTION TO JURISDICTION.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Disclaimer for "AtoZ Cambodias</h1>

				<p class="mb-5 text-sm">
					"AtoZ Cambodia verified means, the information related to name, address, contact details
					of the business establishments have been verified as existing at the time of registering
					any advertiser with AtoZ Cambodia. This verification is solely based on the documents as
					supplied by an advertiser/s or as per the details contained in Customer E-Registration
					Form.
				</p>

				<p class="mb-5 text-sm">
					AtoZ Cambodia strongly recommends to its users/callers to verify all relevant details of
					vendors/services prior to availing any products/services from them. AtoZ Cambodia does not
					implicitly or explicitly endorse any product/s or services provided by the vendors/service
					providers.
				</p>

				<p class="text-sm">
					The "AtoZ Cambodia Certificate is a limited assurance offered by AtoZ Cambodia that the
					name and contact information of the advertiser and the category in which the advertiser is
					listed by AtoZ Cambodia, have been verified as existing and correct at the time of the
					advertiser's application to register with AtoZ Cambodia. AtoZ Cambodia makes no
					representations or warranties, whether express or implied, including but not limited to
					warranties of the continued existence and/or operations of the advertiser, or the quality,
					quantity, merchantability or fitness for use of the goods or services offered by the
					advertiser.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Additional Disclaimer</h1>

				<p class="mb-5 text-sm">
					Users using any of AtoZ Cambodia service across the following mediums ie. through internet
					ie www.AtoZ Cambodia Website, Wapsite, SMS, phone or any other medium are bound by this
					additional disclaimer wherein they are cautioned to make proper enquiry before they
					(Users) rely, act upon or enter into any transaction (any kind or any sort of transaction
					including but not limited to monetary transaction ) with the Advertiser listed with AtoZ
					Cambodia.
				</p>

				<p class="text-sm">
					All the Users are cautioned that all and any information of whatsoever nature provided or
					received from the Advertiser/s is taken in good faith, without least suspecting the
					bonafides of the Advertiser/s and AtoZ Cambodia does not confirm, does not acknowledge, or
					subscribe to the claims and representation made by the Advertiser/s listed with AtoZ
					Cambodia .Further, AtoZ Cambodia is not at all responsible for any act of Advertiser/s
					listed at AtoZ Cambodia.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Limitation of Liability</h1>

				<p class="mb-5 text-sm">
					IN NO EVENT SHALL AtoZ CAMBODIA BE LIABLE TO ANY USER ON ACCOUNT OF SUCH USER'S USE,
					MISUSE OR RELIANCE ON THE PLATFORMS FOR ANY DAMAGES WHATSOEVER, INCLUDING DIRECT, SPECIAL,
					PUNITIVE, INDIRECT, CONSEQUENTIAL OR INCIDENTAL DAMAGES OR DAMAGES FOR LOSS OF PROFITS,
					REVENUE, USE, OR DATA WHETHER BROUGHT IN WARRANTY, CONTRACT, INTELLECTUAL PROPERTY
					INFRINGEMENT, TORT (INCLUDING NEGLIGENCE) OR OTHER THEORY, EVEN IF AtoZ CAMBODIA IS AWARE
					OF OR HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE, ARISING OUT OF OR CONNECTED
					WITH THE USE (OR INABILITY TO USE) OR PERFORMANCE OF THE PLATFORMS, THE MATERIALS OR THE
					INTERNET GENERALLY, OR THE USE (OR INABILITY TO USE), RELIANCE UPON OR PERFORMANCE OF ANY
					MATERIAL CONTAINED IN OR ACCESSED FROM ANY PLATFORMS. AtoZ CAMBODIA DOES NOT ASSUME ANY
					LEGAL LIABILITY OR RESPONSIBILITY FOR THE ACCURACY, COMPLETENESS, OR USEFULNESS OF ANY
					INFORMATION, APPARATUS, PRODUCT OR PROCESS DISCLOSED ON THE PLATFORMS OR OTHER MATERIAL
					ACCESSIBLE FROM THE PLATFORMS.
				</p>

				<p class="text-sm">
					THE USER OF THE PLATFORMS ASSUMES ALL RESPONSIBILITY AND RISK FOR THE USE OF THIS
					PLATFORMS AND THE INTERNET GENERALLY. THE FOREGOING LIMITATIONS SHALL APPLY
					NOTWITHSTANDING ANY FAILURE OF THE ESSENTIAL PURPOSE OF ANY LIMITED REMEDY AND TO THE
					FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW. SOME COUNTRIES DO NOT ALLOW THE EXCLUSION
					OR LIMITATION OF LIABILITY OF CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE EXCLUSIONS
					MAY NOT APPLY TO ALL USERS; IN SUCH COUNTRIES LIABILITY IS LIMITED TO THE FULLEST EXTENT
					PERMITTED BY LAW.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Third Party Sites</h1>

				<p class="mb-5 text-sm">
					Your correspondence or business dealing with or participation in the sales promotions of
					advertisers or service providers found on or through the Platforms, including payment and
					delivery of related goods or services, and any other terms, conditions, and warranties or
					representations associated with such dealings, are solely between you and such advertisers
					or service providers. You assume all risks arising out of or resulting from your
					transaction of business over the Internet, and you agree that we are not responsible or
					liable for any loss or result of the presence of information about or links to such
					advertisers or service providers on the Platforms. You acknowledge and agree that we are
					not responsible or liable for the availability, accuracy, authenticity, copyright
					compliance, legality, decency or any other aspect of the content, advertising, products,
					services, or other materials on or available from such sites or resources. You acknowledge
					and agree that your use of these linked sites is subject to different terms of use than
					these Terms, and may be subject to different privacy practices than those set forth in the
					Privacy Policy governing the use of the Platforms . We do not assume any responsibility
					for review or enforcement of any local licensing requirements that may be applicable to
					businesses listed on the Platforms.
				</p>

				<p class="mb-5 text-sm">
					MONITORING OF MATERIALS TRANSMITTED BY YOU: Changes may be periodically incorporated into
					the Platforms. AtoZ Cambodia may make improvements and/or changes in the products,
					services and/or programs described in these Platforms and the Materials at any time
					without notice. We are under no obligation to monitor the material residing on or
					transmitted to the Platforms . However, anyone using the Platforms agrees that AtoZ
					Cambodia may monitor the Platforms contents periodically to (1) comply with any necessary
					laws, regulations or other governmental requests; (2) to operate the Platforms properly or
					to protect itself and its users. AtoZ Cambodia reserves the right to modify, reject or
					eliminate any material residing on or transmitted to its Platforms that it, in its sole
					discretion, believes is unacceptable or in violation of the law or these Terms and
					Conditions.
				</p>

				<p class="text-sm">
					DELETIONS FROM SERVICE: AtoZ Cambodia will delete any materials at the request of the user
					who submitted the materials or at the request of an advertiser who has decided to
					"opt-out" of the addition of materials to its advertising, including, but not limited to
					ratings and reviews provided by third parties. AtoZ Cambodia reserves the right to delete
					(or to refuse to post to public forums) any materials it deems detrimental to the system
					or is, or in the opinion of AtoZ Cambodia, may be, defamatory, infringing or violate of
					applicable law. AtoZ Cambodia reserves the right to exclude Material from the Platforms.
					Materials submitted to AtoZ Cambodia for publication on the Platforms may be edited for
					length, clarity and/or consistency with AtoZ Cambodia's editorial standards.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Indemnification</h1>

				<p class="text-sm">
					You agree to indemnify and hold us and (as applicable) our parent, subsidiaries,
					affiliates, officers, directors, agents, and employees, harmless from any claim or demand,
					including reasonable attorneys' fees, made by any third party due to or arising out of
					your breach of these Terms, your violation of any law, or your violation of the rights of
					a third party, including the infringement by you of any intellectual property or other
					right of any person or entity. These obligations will survive any termination of the
					Terms.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Miscellaneous</h1>

				<p class="mb-5 text-sm">
					These Terms will be governed by and construed in accordance with the territorial laws,
					without giving effect to its conflict of laws provisions or your actual state or country
					of residence, and you agree to submit to personal jurisdiction. You agree to exclude, in
					its entirety, the application to these Terms of the United Nations Convention on Contracts
					for the International Sale of Goods. You are responsible for compliance with applicable
					laws. If for any reason a court of competent jurisdiction finds any provision or portion
					of the Terms to be unenforceable, the remainder of the Terms will continue in full force
					and effect. These Terms constitute the entire agreement between us and supersedes and
					replaces all prior or contemporaneous understandings or agreements, written or oral,
					regarding the subject matter of these Terms. Any waiver of any provision of the Terms will
					be effective only if in writing and signed by you and AtoZ Cambodia. AtoZ Cambodia
					reserves the right to investigate complaints or reported violations of these Terms and to
					take any action we deem necessary and appropriate. Such action may include reporting any
					suspected unlawful activity to law enforcement officials, regulators, or other third
					parties. In addition, we may take action to disclose any information necessary or
					appropriate to such persons or entities relating to user profiles, e-mail addresses, usage
					history, posted materials, IP addresses and traffic information. AtoZ Cambodia reserves
					the right to seek all remedies available at law and in equity for violations of these
					Terms.
				</p>

				<p class="mb-5 text-sm">
					Notices. All of our notices, demands and other communications must be in writing and will
					be deemed to have been given (a) if mailed by certified mail, postage prepaid, (b) if
					delivered by overnight courier, (c) if sent by facsimile transmission and such
					transmission is confirmed as received, or (d) if sent by electronic mail, and such message
					is confirmed as received, in each case to the address, fax number or e-mail address
					specified on the Order for the recipient of such notice.
				</p>

				<p class="mb-5 text-sm">
					In no event shall we or any Distribution Site have liability or be deemed to be in breach
					hereof for any failure or delay of performance resulting from any governmental action,
					fire, flood, insurrection, earthquake, power failure, network failure, riot, explosion,
					embargo, strikes (whether legal or illegal), terrorist act, labor or material shortage,
					transportation interruption of any kind or work slowdown or any other condition not
					reasonably within our control. Your payment obligations shall continue during any event of
					force majeure. Indemnification. You agree to indemnify us and the Distribution Sites and
					hold us and the Distribution Site harmless from and with respect to any claims, actions,
					liabilities, losses, expenses, damages and costs (including, without limitation, actual
					attorneys' fees) that may at any time be incurred by us or them arising out of or in
					connection with these Terms or any Advertising Products or services you request,
					including, without limitation, any claims, suits or proceedings for defamation or libel,
					violation of right of privacy or publicity, criminal investigations, infringement of
					intellectual property, false or deceptive advertising or sales practices and any virus,
					contaminating or destructive features. Telephone Conversations. All telephone
					conversations between you and us about your advertising may be recorded and you hereby
					consent to such monitoring and recordation.
				</p>

				<p class="mb-5 text-sm">
					These Terms constitute the entire agreement between you and us with respect to the subject
					matter of these Terms and supersedes all prior written and all prior or contemporaneous
					oral communications regarding such subject matter. Accordingly, you should not rely on any
					representations or warranties that are not expressly set forth in these Terms. If any
					provision or provisions of these Terms shall be held to be invalid, illegal, unenforceable
					or in conflict with the law of any jurisdiction, the validity, legality and enforceability
					of the remaining provisions shall not in any way be affected or impaired. Except as
					provided in Section 1, these Terms may not be modified except by writing signed by you and
					us; provided, however, we may change these Terms from time to time, and such revised terms
					and conditions shall be effective with respect to any Advertising Products ordered after
					written notice of such revised terms to you or, if earlier, posting of such revised terms
					and conditions on our Website.
				</p>
			</div>

			<h2 class="mb-5 text-lg font-semibold tracking-wide sm:text-xl">Terms of Service</h2>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">OBLIGATIONS OF AtoZ Cambodia:</h1>

				<ul class="ml-4 flex list-decimal flex-col gap-5 text-sm">
					<li>
						In providing the Services, the AtoZ Cambodia is acting as an Intermediary between the
						Merchant and Customers/Users. The contract for the sale of goods or services will be
						between the Customers/Users and the Merchant. The Merchant shall be solely responsible
						for all customer service issues relating to its supply of goods or services (including
						pricing, rebates, item information, availability, technical support, functionality,
						warranties, guarantees, order fulfillment, shipping, handling, order cancellation,
						returns, refund, adjustments, feedback and product or service complaints). In performing
						customer service, the Merchant shall present itself to its customers AtoZ Cambodia
						Provider. It is the responsibility of the Merchant and not the AtoZ Cambodia to resolve
						any dispute or claim raised by Customers/Users relating to the purchase or sale of goods
						or services from the Merchant.
					</li>

					<li>
						In case of an unauthorized Refund or a Refund that was incorrectly executed due to an
						error by AtoZ Cambodia, AtoZ Cambodia shall at the Merchant's request immediately credit
						to the Merchant Account the refunded amount including all related Service Fees deducted
						therefrom. The AtoZ Cambodia shall not be liable, where the unauthorized Refund arises
						from: (a) the Merchant's failure to keep the personalized security features of the
						Merchant’s Account safe in accordance security policies prescribed under the law time
						being in force; or (b) any breach of this Agreement by the Merchant, or the Merchant 's
						negligence or willful misconduct; (c) if the Merchant fails to notify the AtoZ Cambodia
						of any loss of the Merchant's Password or other event that could reasonably be expected
						to have compromised the security of the Merchant Account after the Merchant has gained
						knowledge of such event; or (d) the Merchant fails to dispute and bring the unauthorized
						or incorrectly executed transaction to the AtoZ Cambodia’s attention within 24 (Twenty
						Four) Hours from the time/date of the transaction.
					</li>

					<li>
						AtoZ Cambodia is obligated to perform only those duties expressly described in this
						Agreement. AtoZ Cambodia shall not be liable for any error in judgment, for any act
						taken or not taken, or for any mistake of fact , except for as expressly provided for
						herein.
					</li>

					<li>
						AtoZ Cambodia shall maintain daily transaction records for accounting purposes and data
						and information generated/maintained by AtoZ Cambodia under this agreement shall prevail
						and be binding on the parties.
					</li>

					<li>
						AtoZ Cambodia hereby agrees that the payment identification number generated by AtoZ
						Cambodia shall be the proof of payment made by AtoZ Cambodia to Merchant.
					</li>
				</ul>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Privacy</h1>

				<ul class="ml-4 flex list-decimal flex-col gap-5 text-sm">
					<li>
						Your privacy is very important to us. Your accounts details in as much as the services
						under this terms of services are safe and secure with us.
					</li>

					<li>
						By using our Service, you may receive information about Customers. You must keep such
						information confidential and only use it in connection with the Services. You may not
						disclose or distribute any such information to a third party or use the information for
						marketing purposes unless you receive the express consent of the Customer.
					</li>
				</ul>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Obligations Towards Financial Institution Partners</h1>

				<p class="text-sm">
					As you will be using the AtoZ Cambodia services, you must comply with all applicable
					rules, guidelines, instructions, requests and actions, etc., made by the Financial
					Institution Partners from time to time. The Financial Institution Partners may also put
					limitations and restrictions on you, at its sole discretion. In addition, the Financial
					Institution Partner has the right to reverse/reject settlement, suspend and/or terminate
					services, make inspections or inquiries in relation to the Transaction, etc. You
					understand and acknowledge that the Financial Institution Partners Rules form a part of
					this Agreement. In the event that your non-compliance of Financial Institution Partners
					Rules, results in any fines, penalties or other amounts being levied on or demanded of
					AtoZ Cambodia by an Financial Institution Partners, then without prejudice to AtoZ
					Cambodia’s other rights hereunder, you shall forthwith indemnify AtoZ Cambodia in an
					amount equal to the fines, penalties or other amount so levied or demanded. If you fail to
					comply with your obligations towards the Financial Institution Partners, AtoZ Cambodia may
					suspend settlement or suspend/terminate the AtoZ Cambodia Services forthwith.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Connectivity and Integrity of Hotlink</h1>

				<ul class="ml-4 flex list-decimal flex-col gap-5 text-sm">
					<li>
						You shall be responsible at your own costs for providing and maintaining all necessary
						equipment, software and facilities at your end so as to connect the AtoZ Cambodia Pay
						Service.
					</li>

					<li>
						You shall be responsible at your own costs for providing and maintaining all necessary
						equipment, software and facilities at your end so as to connect the AtoZ Cambodia Pay
						Service.
					</li>

					<li>
						You shall take all such precautions and measures as may be directed by AtoZ Cambodia
						from time to time to ensure that there is no breach of security and the integrity of the
						link. You shall also ensure that there are proper encryption and robust security
						measures to prevent any hacking into the information of the Customers and other data. In
						addition to the above, you shall also comply with security practices and procedures as
						prescribed in the Information Technology Act, 2000 and the rules made thereunder and/or
						the RBI rules and Regulations. Any loss incurred to you, AtoZ Cambodia or Financial
						Institution Partner as a result of the Hotlink being breached due to improper security
						on part of you, your employees, contractors, agents, etc, shall be borne solely by you
						and you agree to indemnify, defend and hold harmless AtoZ Cambodia and the Financial
						Institution Partner from any claims, actions, damages or losses arising out or in
						relation thereto.
					</li>

					<li>
						Without prejudice to the generality of the aforesaid, you shall routinely and at such
						time intervals as may be specified by AtoZ Cambodia check the integrity of the Hotlink
						and provide such reports from time to time.
					</li>
				</ul>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Publicity</h1>

				<p class="text-sm">
					Merchant hereby agrees and confirms to include the name and logo of AtoZ Cambodia/AtoZ
					Cambodia Pay Services in all of their advertisement / promotional material upon taking
					written consent from AtoZ Cambodia in writing .
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Representation, Covenants and Warranties of Merchant:</h1>

				<ul class="ml-4 flex list-decimal flex-col gap-5 text-sm">
					<li>
						Merchant has all the necessary licenses, permissions, approvals, rights and is fully
						authorized to sell the products/services to customers;
					</li>

					<li>
						Merchant has full corporate power and authority to execute, deliver and perform this
						Agreement;
					</li>

					<li>
						Merchant has obtained all licenses, clearances, permissions, approvals or consents from
						any third party or any regulatory or government body which are required by applicable
						law or regulations, to execute the business/services of this Agreement.
					</li>

					<li>
						Merchant confirms that, the execution of this Agreement and the performance of its
						obligations under this Agreement and the implementations of the terms and conditions
						contemplated hereby do not constitute a breach of any contract, agreement, arrangement
						or understanding, entered into by it with any third party, or any IPR of any third
						party;
					</li>

					<li>
						Merchant confirms that the execution of this Agreement and the performance of its
						obligations under this Agreement and the implementations of the terms and conditions
						contemplated hereby does not violate any statute, regulation, rule, order, decree,
						injunction or other restriction of any governmental agency or Court or any regulatory
						authority to which it is subject or any of the provisions of its’ constitutional
						documents.
					</li>

					<li>
						Merchant shall post its refund/cancellation policy on its Website and shall ensure that
						its Customers are bound by the refund/cancellation policy. Merchant agrees to put up
						such notices, disclaimers or warranties as may be required under the law and/or by AtoZ
						Cambodia.
					</li>

					<li>
						Merchant hereby agrees that AtoZ Cambodia does not verify the identity of Users of the
						Service and that the information provided to Merchant is the information received from
						the User/customer which has not been independently verified by AtoZ Cambodia.
					</li>

					<li>
						In consideration of AtoZ Cambodia providing the services as provided under this
						agreement, Merchant shall at all times use the logo of AtoZ Cambodia / AtoZ Cambodia Pay
						services in all their promotional material and in their advertisement after taking the
						written consent from AtoZ Cambodia.
					</li>
				</ul>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Ownership and Intellectual Property Rights</h1>

				<ul class="ml-4 flex list-decimal flex-col gap-5 text-sm">
					<li>
						Both the Parties hereby acknowledge and agree that each Party is the absolute owner of
						all right, title and interest in respect of their own trade name, logo, trademark,
						copyright, device, label, color combination, artwork and visual representation and they
						shall not, by virtue of this Agreement, assume activities under this Agreement or
						affiliation with the other Party, acquire or claim any interest in any such trade names
						or copyright belonging to and/or owned by the other Party.
					</li>

					<li>
						Each Party shall at all times render assistance in its power to restrain the
						infringement, passing-off, duplication, unauthorized use or colorable imitation of any
						such trade descriptions, logo, device, label, art work, trade names, trademarks or
						Copyrights.
					</li>

					<li>
						Each Party hereby agrees and undertakes that it shall not register, use or file and/ or
						assist in and/ or allow registering, using or filing, either directly or indirectly, for
						itself or through, on behalf of or in conjunction with any person or legal entity and
						whether as principal, agent, shareholder, consultant, employee or in any capacity
						whatsoever, any trademarks/ service marks in any class, either alone or in combination
						with any other mark or material, which is similar and or identical and/ or resembling in
						any manner with the other party’s marks and/ or intellectual property rights of the
						other party and not to associate the other party marks and/ or intellectual property
						rights of the other party with its own business and/ or the business of any third party
						associated with it, except as contemplated under this Agreement.
					</li>

					<li>
						Upon the termination of this Agreement for any reason, the Parties shall immediately
						cease to use the other party’s marks and/ or intellectual property rights vested in the
						other party in any manner whatsoever.
					</li>

					<li>
						Either Party shall not claim any right, title, or interest in the other party's marks
						and/ or intellectual property rights vested in the other party and the same shall at all
						times continue to be the exclusive property of the other party.
					</li>

					<li>
						Either party shall not directly or indirectly do anything which shall have an adverse
						impact on the other party’s marks and/ or intellectual property rights and/ or
						confidential information of the other party. In the event of termination of this
						Agreement the provisions of this Clause 10 shall survive the termination of this
						Agreement.
					</li>
				</ul>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Confidentiality</h1>

				<ul class="ml-4 flex list-decimal flex-col gap-5 text-sm">
					<li>
						Except as specifically set out in this Agreement, no announcement or communication
						concerning the terms of this Agreement shall be made or caused to be made before or
						after the execution of this Agreement, by both Parties without mutual consent.
					</li>

					<li>
						<h6 class="mb-5 text-sm">
							Both Parties have agreed that, save and except with the prior written consent of the
							other Party:
						</h6>

						<ul class="ml-4 flex list-disc flex-col gap-5 text-sm">
							<li>
								On and from the date of this Agreement, the contents of this Agreement and any
								documents, data, or information, which a Party may obtain from the other Party
								pursuant to this Agreement, or sensitive personal data and information defined under
								the Information Technology (reasonable security practices and procedure and
								sensitive personal data or information) Rule, 2011 (hereinafter referred to as
								"Confidential Information") shall be kept confidential and shall not be disclosed by
								either Party to any third party.
							</li>

							<li>
								Upon the expiry of the term of this Agreement or the termination of this Agreement,
								neither Party shall issue any adverse official written communication relating to
								such termination or the factum of this Agreement.
							</li>

							<li>
								However, the Parties may disclose such Confidential Information under following
								circumstances: (i) if it is essential for the assessment of the transaction to
								disclose Confidential Information, (ii) may disclose such Confidential Information
								to its employees, agents and advisors (including without limitation, attorneys,
								accountants, consultants, bankers, financial advisors, or their representatives)
								whose knowledge of the Confidential Information is essential for fulfilling its
								obligations under the Agreement; (iii) disclose the said confidential Information to
								lawful authority after getting the lawful order; & (iv) where the disclosure is
								necessary for compliance of a legal obligation. Subject to the aforesaid conditions,
								the Parties shall not under any circumstances disclose to any third party or to any
								other AtoZ Cambodia the terms and conditions of this Agreement & all confidential
								Information, documents, manuals and other materials provided by the other Party,
								during the subsistence & survival of this Agreement.
							</li>
						</ul>
					</li>

					<li>
						Upon the expiration, cancellation or termination of this Agreement, each Party shall
						forthwith stop using and, return or destroy all Confidential Information, documents,
						manuals and other materials provided by the other Party. Upon request, the receiving
						Party shall send the disclosing Party a certificate specifying that all the Confidential
						Information, documents, manuals and other materials have either been destroyed or
						returned.
					</li>

					<li>
						In the event either Party violates or causes to be violated any of the provisions of
						this Clause during the term of this Agreement and after its expiry or sooner
						termination, the other Party shall, without prejudice to its other rights to claim
						injunctive relief, be entitled to claim from the Party in breach, and the Party in
						breach shall be liable to pay to the other Party as liquidated damages, compensation to
						the tune of actual amount of damages as determined and supported by proof of evidence,
						by the other Party. The above clause shall survive for the period of three years after
						the termination of the Agreement.
					</li>

					<li>
						Duty or misrepresentation, or otherwise, shall be limited to an amount not more than the
						payment made by the customers/users in the one month immediately prior to the date on
						which the cause of action for such liability arose;
					</li>
				</ul>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Term</h1>

				<p class="text-sm">
					This Agreement shall remain in force continuously from the date of execution of this
					Agreement, until and unless otherwise terminated by either party by giving 30 (Thirty)
					days prior written notice to the other party. The duration may be reduced as mutually
					decided by both the parties.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Termination</h1>

				<ul class="ml-4 flex list-decimal flex-col gap-5 text-sm">
					<li>
						Each party shall have the option to terminate this Agreement at any time by giving 30
						(thirty) days advance notice in writing to that effect to the other party.
					</li>

					<li>
						The Parties have right to terminate this Agreement forthwith by a notice in writing to
						the other Party, if other Party has committed any material breach of its obligations
						specified under this Agreement or has violated any law under which its right to business
						may cease and has failed to remedy the highlighting such breach or non-performance
						within one week.
					</li>

					<li>
						Each Party shall have the option to terminate this Agreement, by giving notice in
						writing, in the event that any other Party becomes insolvent, goes into liquidation or a
						liquidator is appointed to wind up the Company.
					</li>

					<li>
						This Agreement shall stand terminated automatically if the business of the merchant
						becomes illegal/unlawful/banned by the law of the land or if the Merchant indulges in
						any illegal act or practice that makes its business illegal/unlawful/banned or if any
						transaction has taken place which results directly or indirectly in Money Laundering
						activities or financing of terrorists activities. AtoZ Cambodia shall not be liable for
						such activities/transactions and Merchant shall be solely responsible / liable for any
						action taken by any Government or regulatory authority.
					</li>

					<li>
						In the event of the termination of this Agreement either Party will, forthwith return
						all the signage, literature, banners, glow-signs and any such other promotional material
						to other party. The termination shall not affect any liabilities incurred by the either
						Parties prior to the termination of the Agreement or for acts performed during the
						pendency of the Agreement which may result in a dispute post termination of the
						Agreement nor any provision expressed to survive or to be effective on termination and
						the obligations set out in this clause shall remain in full force and effect
						notwithstanding termination.
					</li>
				</ul>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">General Provisions</h1>

				<ul class="ml-4 flex list-decimal flex-col gap-5 text-sm">
					<li>
						<b>Assignment : </b>

						Neither Party shall assign the obligations nor any of the benefits under this Agreement
						to any persons, firm or company, save and except with prior written permission from the
						other party.
					</li>

					<li>
						<b>Waivers : </b>

						Waivers: No waiver by either party of any of their terms hereof or of any breach thereof
						shall constitute or be deemed to be a waiver of any such terms or of any breach in any
						other case whether prior or subsequent thereto.
					</li>

					<li>
						<b>Force Majeure : </b>

						Neither party to this Agreement shall be responsible for any delay in the performance of
						any terms and conditions hereunder to the extent that such delay is caused by war,
						revolution, riot, act of public enemy, terrorism, sabotage, epidemic, quarantine
						restrictions, accident, fire flood, tempest, earthquake, civil commotion, governmental
						action, Acts of God (force majeure ) including, but not restricted to, strike, lock-out,
						fire, break-down, war, destruction of network, web space or website by way of hacking,
						virus prone, defacement, stoppage of display or transmission of the website/app of AtoZ
						Cambodia, Act, or Regulation, or restriction of Government, inability to secure
						Government authorization, or approval, or any other cause beyond their reasonable
						control, including the breakdown of systems and any other causes beyond its reasonable
						control.

						<br />
						<br />

						If at any time during the term of this agreement the performance in whole or in part by
						any one of the parties, of any obligation under this agreement is prevented or delayed
						by reason of war, revolution, riot, act of public enemy, terrorism, sabotage, epidemic,
						quarantine restrictions, accident, fire flood, tempest, earthquake, civil commotion,
						governmental action or Act of God, the other party shall not be entitled to terminate
						this agreement neither shall any party have any claim for damages against the other in
						respect of such non-performance or delay in performance, provided notice of the
						happening of any such event/s is given by the affected party to the other within twenty
						one (21) days from the date of occurrence.
					</li>

					<li>
						<b>Notice : </b>

						Delivery of Notice: All notices or other communications required to be given hereunder
						shall be in writing and delivered either personally or by registered A.D. and /or mail,
						certified, return receipt requested postage prepaid, and addressed as provided in this
						Agreement or as otherwise requested by the receiving party. Notices delivered personally
						shall be effective upon delivery and notices delivered by mail shall be effective upon
						their receipt by the party to whom it is addressed. The Parties shall notify any change
						in address to the other party promptly. In case of failure to inform the other Party
						about the change of address, the notice shall be served to the address mentioned in this
						agreement and shall be treated as properly served.
					</li>

					<li>
						<b> Entire Agreement : </b>

						This Agreement constitutes the entire Agreement between Merchant and the AtoZ Cambodia
						pertaining to the subject matter hereof and supersedes in their entirety all written or
						oral agreements between the parties.
					</li>

					<li>
						<b> Severability : </b>

						If any provision of this Agreement is determined to be unenforceable for any reason,
						then the remaining provisions hereof shall remain unaffected and in full force and
						effect.
					</li>

					<li>
						<b> Variations of Agreement : </b>

						No variation or amendment to this Agreement shall bind either party unless made in
						writing and signed by the duly authorized persons/officers of both the parties.
					</li>

					<li>
						<b> Jurisdiction : </b>

						It is mutually agreed between the parties hereto that any dispute or claim arising under
						this Agreement shall be subject to the jurisdiction of the Courts of Odisha.
					</li>
				</ul>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Annexure ‘A’</h1>

				<p class="mb-5 text-sm">
					Banned/Prohibited list of Products and Services referred to in this Agreement is as
					mentioned herein below:-
				</p>

				<ul class="ml-4 flex list-decimal flex-col gap-5 text-sm">
					<li>
						Adult goods and services which includes pornography and other sexually suggestive
						materials (including literature, imagery an d other media); escort or prostitution
						services; website access and/or website memberships of pornography or illegal sites.
					</li>

					<li>
						Alcohol which includes Alcohol or alcoholic beverages such as beer, liquor, wine, or
						champagne.
					</li>

					<li>Body parts which include organs or other body parts.</li>

					<li>
						Bulk marketing tools which include email lists, software, or other products enabling
						unsolicited email messages (spam).
					</li>

					<li>
						Cable descramblers and black boxes which includes devices intended to obtain cable and
						satellite signals for free.
					</li>

					<li>Child pornography which includes pornographic materials involving minors.</li>

					<li>
						Copyright unlocking devices which includes Mod chips or other devices designed to
						circumvent copyright protection
					</li>

					<li>
						Copyrighted media which includes unauthorized copies of books, music, movies, and other
						licensed or protected materials
					</li>

					<li>
						Copyrighted software which includes unauthorized copies of software, video games and
						other licensed or protected materials, including OEM or bundled software.
					</li>

					<li>
						Counterfeit and unauthorized goods which includes replicas or imitations of designer
						goods; items without a celebrity endorsement that would normally require such an
						association; fake autographs, counterfeit stamps, and other potentially unauthorized
						goods.
					</li>

					<li>
						Drugs and drug paraphernalia which includes illegal drugs and drug accessories,
						including herbal drugs like salvia and magic mushrooms.
					</li>

					<li>
						Drug test circumvention aids which includes drug cleansing shakes, urine test additives,
						and related items.
					</li>

					<li>
						Endangered species which includes plants, animals or other organisms (including product
						derivatives) in danger of extinction.
					</li>

					<li>
						Gaming/gambling which includes lottery tickets, sports bets, memberships/ enrollment in
						online gambling sites, and related content.
					</li>

					<li>
						Government IDs or documents which include fake IDs, passports, diplomas, and noble
						titles.
					</li>

					<li>
						Hacking and cracking materials which includes manuals, how-to guides, information, or
						equipment enabling illegal access to software, servers, website, or other protected
						property.
					</li>

					<li>
						Illegal goods which includes materials, products, or information promoting illegal goods
						or enabling illegal acts.
					</li>

					<li>
						Miracle cures which include unsubstantiated cures, remedies or other items marketed as
						quick health fixes.
					</li>

					<li>
						<h6 class="mb-5 text-sm">
							Offensive goods which includes literature, products or other materials that:
						</h6>

						<ul class="ml-4 flex list-disc flex-col gap-5">
							<li>
								Defame or slander any person or groups of people based on race, ethnicity, national
								origin, religion, sex, or other factors
							</li>

							<li>Encourage or incite violent acts</li>

							<li>Promote intolerance or hatred.</li>
						</ul>
					</li>

					<li>
						Offensive goods, crime which includes crime scene photos or items, such as personal
						belongings, associated with criminals.
					</li>

					<li>
						Prescription drugs or herbal drugs or any kind of online pharmacies which includes drugs
						or other products requiring a prescription by a licensed medical practitioner.
					</li>

					<li>
						Pyrotechnic devices, combustibles, corrosives and hazardous materials which includes
						explosives, fireworks and related goods; toxic, flammable, and radioactive materials and
						substances.
					</li>

					<li>
						Regulated goods which includes air bags; batteries containing mercury; Freon or similar
						substances/refrigerants; chemical/industrial solvents; government uniforms; car titles;
						license plates; police badges and law enforcement equipment; lock-picking devices;
						pesticides; postage meters; recalled items; slot machines; surveillance equipment; goods
						regulated by government or other agency specifications.
					</li>

					<li>Securities which includes stocks, bonds, or related financial products.</li>

					<li>
						Traffic devices which includes radar detectors/jammers, license plate covers, traffic
						signal changers, and related products.
					</li>

					<li>
						Weapons which includes firearms, ammunition, knives, brass knuckles, gun parts, and
						other armaments.
					</li>

					<li>Wholesale currency which includes discounted currencies or currency exchanges.</li>

					<li>Live animals or hides/skins/teeth, nails and other parts etc of animals.</li>

					<li>Multi Level Marketing collection fees.</li>

					<li>Matrix sites or sites using a matrix scheme approach.</li>

					<li>Work-at-home approach and/or Work-at-home information.</li>

					<li>
						Any product or service which is not in compliance with all applicable laws and
						regulations whether federal, state, local or international including the laws of India.
					</li>

					<li>
						Merchant providing services that have the potential of casting AtoZ Cambodia and/or
						Payment System Providers in a poor light and/or that may be prone to ―Buy & Deny‖
						attitude of the cardholders when billed (e.g. Adult material/ mature content/Escort
						services/ friend finders) and thus leading to chargeback and fraud losses.
					</li>

					<li>
						Businesses or websites that operate within the scope of laws which are not absolutely
						clear or are ambiguous in nature (e.g. Web-based telephony, websites supplying medicines
						or controlled substances, websites that promise online match-making).
					</li>

					<li>
						Businesses out rightly banned by law (e.g. Betting & Gambling/ publications or content
						that is likely to be interpreted by the authorities as leading to moral turpitude or
						decadence or incite caste/communal tensions, lotteries/sweepstakes & games of chance.
					</li>

					<li>
						Merchant who deal in intangible goods/ services (eg. software download/ Health/ Beauty
						Products), and businesses involved in pyramid marketing schemes or get-rich-quick
						schemes. Any other product or Service, which in the sole opinion of either AtoZ Cambodia
						or Payment System Providers , is detrimental to the image and interests of either of
						them / both of them, as communicated by either of them/ both of them to Merchant from
						time to time. This shall be without prejudice to any other terms & conditions mentioned
						in this Agreement.
					</li>

					<li>
						Bulk marketing tools which include email, lists, software, or other products enabling
						unsolicited email messages (spam).
					</li>

					<li>
						Web-based telephony/ SMS/Text/Facsimile services or Calling Cards. Bandwidth or Data
						transfer/ allied services. Voice process /knowledge process services.
					</li>
				</ul>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Documentations</h1>

				<ul class="ml-4 flex list-decimal flex-col gap-5 text-sm">
					<li>
						The collection, verification, audit and maintenance of correct and updated Customer
						information is a continuous process and AtoZ Cambodia reserves the right, at any time,
						to take steps necessary to ensure compliance with all relevant and applicable KYC
						requirements. AtoZ Cambodia reserves the right to discontinue services/ reject
						applications for AtoZ Cambodia Services at any time if there are discrepancies in
						information and/or documentation provided by you.
					</li>

					<li>
						Any information provided to AtoZ Cambodia with the intention of securing AtoZ Cambodia
						Services shall vest with AtoZ Cambodia, and may be used by AtoZ Cambodia, for any
						purpose consistent with any applicable law or regulation, at its discretion.
					</li>

					<li>
						Once you have successfully created an Account after completing the registration process
						in accordance with these T&Cs, you can start availing of our AtoZ Services.
					</li>

					<li>
						Once you have successfully created an Account after completing the registration process
						in accordance with these T&Cs, you can start availing of our AtoZ Cambodia Services.
					</li>
				</ul>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Your Use of Our Information</h1>

				<p class="text-sm">
					Except for Posted Information that you submit, all of the information available on or
					through the Services and/or the Website, including without limitation, text, photographs,
					graphics and video and audio content, is owned by us and our licensors and is protected by
					copyright, trademark, patent and trade secret laws, other proprietary rights and
					international treaties. You acknowledge that the Services and any underlying technology or
					software used in connection with the Services contain AtoZ Cambodia's proprietary
					information. We give you permission to use the aforementioned content for personal,
					non-commercial purposes only and do not transfer any intellectual property rights to you
					by virtue of permitting your use of the Services. You may not copy, distribute, republish
					(except as permitted in this paragraph), sell, or exploit any of the content, or exploit
					the Website in whole or in part, for any commercial gain or purpose whatsoever. Except as
					is expressly and unambiguously provided herein, we do not grant you any express or implied
					rights, and all rights in the Website and the Services not expressly granted by us to you
					are retained by AtoZ Cambodia.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Termination/Suspension of Service</h1>

				<ul class="ml-4 flex list-decimal flex-col gap-5 text-sm">
					<li>
						We may suspend or terminate your access to the AtoZ Cambodia Services without notice
						where it is reasonable for us to do so and specifically if: (i) for any reason we decide
						to discontinue to provide the AtoZ Cambodia , (ii) we believe that you have breached any
						of the terms of this Agreement, (iii) your use of the AtoZ Cambodia has been in any way
						improper or breaches the spirit of this Agreement, (iv) we reasonably believe use of the
						AtoZ Cambodia may be at risk of fraud or misuse; (v) our information technology
						infrastructure has failed, is experiencing outages or requires maintenance; or (vi)
						ordered or recommended to do so by the security services, court or a relevant regulatory
						authority.
					</li>

					<li>
						<h6 class="mb-5 text-sm">
							AtoZ Cambodia reserves the right to suspend/discontinue AtoZ Cambodia Services to you
							at any time, for any cause, including, but not limited, to the following-
						</h6>

						<ul class="ml-4 flex list-disc flex-col gap-5">
							<li>
								For any suspected violation of the rules, regulations, orders, directions,
								notifications issued by the statutory bodies from time to time or for any violation
								of the terms and conditions mentioned in this document.
							</li>

							<li>
								For any suspected discrepancy in the particular(s), documentation or registration
								Form provided by you;
							</li>

							<li>
								To combat potential fraud, sabotage, willful destruction, threat to national
								security or for any other force majeure reasons etc;
							</li>

							<li>
								If the same is due to technical failure, modification, upgradation, variation,
								relocation, repair, and/or maintenance due to any emergency or for any technical
								reasons.
							</li>

							<li>
								If the same is due to any transmission deficiencies caused by topographical and
								geographical constraints/limitations;
							</li>

							<li>
								If the mobile connection with which your AtoZ Cambodia Services is related ceases to
								be operational or in your possession or control.
							</li>

							<li>
								If AtoZ Cambodia believes, in its reasonable opinion, that cessation/ suspension is
								necessary.
							</li>
						</ul>
					</li>
				</ul>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Third Party Information of The Website</h1>

				<ul class="ml-4 flex list-decimal flex-col gap-5 text-sm">
					<li>
						As some information appearing on the Website is provided to AtoZ Cambodia by third
						parties, AtoZ Cambodia will have no liability in respect of any loss or damage arising
						from third party information which appears on the Website, including the manner in which
						the information is displayed or information which may be: Out of date; Inaccurate;
						Duplication; Impersonation by a person to be another person.
					</li>

					<li>
						All dealings and communication arising from AtoZ Cambodia's facilitation of interaction
						between Merchant and users will be between the Merchant and users only and AtoZ Cambodia
						is not responsible in any manner for any communication between the users and the
						Merchant, and has no liability in respect of such dealings whatsoever. AtoZ Cambodia is
						not an agent for any of the Merchants listed on this Website and AtoZ Cambodia has no
						responsibility for and no liability whatsoever in respect of the conduct of a Merchant
						or quality of service provided by a Merchant.
					</li>
				</ul>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Additional T & Cs</h1>

				<ul class="ml-4 flex list-decimal flex-col gap-5 text-sm">
					<li>
						When you acquire goods, software or any other services from a Merchant Establishment
						through any of AtoZ Cambodia's Services, you understand and agree that, AtoZ Cambodia is
						not a party to the contract between you and the Merchant Establishment. Furthermore,
						AtoZ Cambodia is under no obligation to monitor the Merchant Establishment’s service
						used by you; the Merchant Establishment alone will be responsible for all obligations
						under the contract including (without limitation) warranties or guarantees. Any dispute
						with or complaint against any Merchant Establishment must be directly resolved by the
						Customer with the Merchant Establishment. It is clarified that AtoZ Cambodia shall not
						be responsible or liable for any deficiency in goods and/or services purchased using
						AtoZ Cambodia Services. This exclusion of liability shall apply even for goods and/or
						services made available by AtoZ Cambodia under promotional schemes. You are instructed
						to satisfy yourself regarding the quality, quantity and fitness of any good and/or
						service before purchasing the same.
					</li>

					<li>
						Any amount transferred erroneously by the Customer to any Merchant Establishment shall
						not be refunded to the Customer by AtoZ Cambodia in any circumstances.
					</li>

					<li>
						In the event of any dispute, AtoZ Cambodia records shall be binding as the conclusive
						evidence of the Transactions carried out through use of AtoZ Cambodia Services.
					</li>

					<li>
						AtoZ Cambodia shall send all customer communications by SMS and/or email/link and the
						SMS/link/email shall be deemed to have been received by you after they have been
						submitted for delivery to the mobile phone operator.
					</li>

					<li>
						You agree to receive all commercial messages including transactional messages from AtoZ
						Cambodia.
					</li>
				</ul>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Disclaimer</h1>

				<ul class="ml-4 flex list-decimal flex-col gap-5 text-sm">
					<li>
						WE MAKE NO WARRANTY, EXPRESS OR IMPLIED, WITH RESPECT TO THE SITE, THE PLATFORM/NETWORK
						AND SERVICES OFFERED. WE EXPRESSLY DISCLAIM THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
						MERCHANTABILITY, AND FITNESS FOR ANY PARTICULAR PURPOSE.
					</li>

					<li>
						THE AtoZ Cambodia SERVICES IS PROVIDED "AS IS" "WHERE IS", "WITH ALL FAULTS" BASIS. WE
						MAKE NO WARRANTY OR REPRESENTATION, WHETHER EXPRESS OR IMPLIED, IN RELATION TO THE
						SATISFACTORY QUALITY, FITNESS FOR PURPOSE, COMPLETENESS OR ACCURACY OF THE SERVICE
						OFFERED THROUGH THE AtoZ Cambodia.
					</li>

					<li>
						WE MAKE NO WARRANTY THAT THE OPERATION OF THE AtoZ Cambodia WILL BE UNINTERRUPTED,
						TIMELY, SECURE OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SOFTWARE OR
						THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR BUGS ,OR REPRESENT THE FULL
						FUNCTIONALITY, ACCURACY, RELIABILITY OF THE MATERIALS THEREIN.
					</li>
				</ul>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Limitation of Liability</h1>

				<p class="text-sm">
					NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, NEITHER AtoZ Cambodia, NOR ITS
					AFFILIATED COMPANIES, SUBSIDIARIES, OFFICERS, DIRECTORS, EMPLOYEES OR ANY RELATED PARTY
					SHALL HAVE ANY LIABILITY TO USERS OR TO ANY THIRD PARTY FOR ANY INDIRECT, INCIDENTAL,
					SPECIAL OR CONSEQUENTIAL DAMAGES OR ANY LOSS OF REVENUE OR PROFITS ARISING UNDER OR
					RELATING TO THESE TERMS, THE SITE OR THE OFFERINGS, EVEN IF ANY OF SAID PARTIES HAD BEEN
					ADVISED OF, KNEW OF, OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Indemnity</h1>

				<p class="text-sm">
					You agree to indemnify, defend and hold AtoZ Cambodia and/or related parties harmless from
					any and all claims, losses, damages, and liabilities, penalty, costs and expenses,
					including and without limitation legal fees and expenses, arising out of or related to
					your use or misuse of the AtoZ Cambodia Services, any breach of these Terms and
					Conditions, or any breach of the representations, warranties, and covenants made by you.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Compliance with Law</h1>

				<p class="text-sm">
					AtoZ Cambodia shall comply with the laws as applicable for the time being in force.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Confidentiality</h1>

				<p class="text-sm">
					You specifically agree that in order to facilitate the provision of AtoZ Cambodia
					Services, AtoZ Cambodia may be required to disclose any information or particulars
					pertaining to you to any authority, statutory or otherwise.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Intellectual Property Rights</h1>

				<p class="text-sm">
					The AtoZ Cambodia hereby grants you the non-exclusive, non-transferable right to use our
					AtoZ Cambodia services in accordance with this Agreement. We, or our licensors, own all
					right, title and interest, including, but not limited to all copyright, trademark, patent,
					trade secret or other proprietary rights ("IP Rights"), in and to the website, the Usage
					Data or AtoZ Cambodia Pay services. You shall not reproduce, distribute, transmit, modify,
					create derivative works, display, perform or otherwise use the Site, the Platform or any
					of the IP Rights, or attempt to reverse engineer, decompile, disassemble, or derive the
					source code for the AtoZ Cambodia Pay to create a competing product. You hereby
					acknowledge that by using the AtoZ Cambodia Pay services, you obtain no rights in the
					software, trademarks or content related to the AtoZ Cambodia Pay and you may only use the
					same in accordance with this Agreement. Unauthorized use is strictly prohibited. All
					rights are expressly reserved to AtoZ Cambodia.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">Force Majeure</h1>

				<p class="text-sm">
					AtoZ Cambodia shall not be responsible for any delay in the performance of any terms and
					conditions hereunder to the extent that such delay is caused by technical issue, server
					malfunction, war, revolution, riot, act of public enemy, terrorism, sabotage, epidemic,
					quarantine restrictions, accident, fire flood, tempest, earthquake, civil commotion,
					governmental action, Acts of God (force majeure ) including, but not restricted to,
					strike, lock-out, fire, break-down, war, destruction of network, web space or website by
					way of hacking, virus prone, defacement, stoppage of display or transmission of the
					website/app of AtoZ Cambodia, Act, or Regulation, or restriction of Government, inability
					to secure Government authorization, or approval, or any other cause beyond their
					reasonable control, including the breakdown of systems and any other causes beyond its
					reasonable control.
				</p>
			</div>

			<div class="mb-10">
				<h1 class="mb-5 font-semibold">General</h1>

				<ul class="ml-4 flex list-decimal flex-col gap-5 text-sm">
					<li>
						We reserve the right to modify or terminate the AtoZ Cambodia Pay Services at any time,
						without notice, and we will not be liable to you as a result of any such action.
					</li>

					<li>
						AtoZ Cambodia shall have the right to assign/transfer these presents to any third party
						including its holding company, subsidiaries, affiliates, associates group companies.
					</li>

					<li>
						This Agreement constitutes the entire Agreement between Merchant and the AtoZ Cambodia
						pertaining to the subject matter hereof and supersedes in their entirety all written or
						oral agreements between the parties.
					</li>

					<li>
						The Parties to this Agreement are independent contractors and nothing in this Agreement
						shall make them joint ventures, partners, employees, agents, associates, affiliates or
						other representatives of the other party hereto.
					</li>

					<li>
						To the maximum extent permitted by law, you waive, release, discharge and hold harmless
						AtoZ Cambodia, its affiliated and subsidiary companies, and each of their directors,
						officers, employees, and agents, from any and all claims, losses, damages, liabilities,
						expenses and causes of action arising out of your use of the Platform/ AtoZ Cambodia
						Services.
					</li>

					<li>
						If any provision of this Agreement is determined to be unenforceable for any reason,
						then the remaining provisions hereof shall remain unaffected and in full force and
						effect.
					</li>

					<li>
						In this Agreement and unless otherwise stated, "we", "us" or "our" refers collectively
						to the AtoZ Cambodia and its subsidiaries, affiliates, directors, officers, employees,
						agents and contractors.
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
